/**
 * Anthropic Authentication Module
 * 
 * Supports both API key and OAuth token authentication.
 * OAuth tokens are generated by `claude setup-token` command from Claude Code CLI.
 * 
 * Key Differences:
 * - API Key: sk-ant-... (traditional, via console.anthropic.com)
 * - OAuth Token: Longer format, from Claude CLI integration
 * 
 * @module services/anthropic-auth
 */

import Anthropic from "@anthropic-ai/sdk";
import { getConfigValue } from "../config";
import { logger } from "../logger";

export interface AnthropicConfig {
  authType: "api_key" | "oauth_token";
  credential: string;
}

/**
 * Detect authentication type based on credential format
 * 
 * API Key format: sk-ant-api03-... (40-100 chars, starts with sk-ant-)
 * OAuth Token: Longer format (100+ chars), different prefix pattern
 */
export function detectAuthType(credential: string): "api_key" | "oauth_token" {
  // API keys typically start with sk-ant- and are shorter
  if (credential.startsWith("sk-ant-")) {
    return "api_key";
  }
  
  // OAuth tokens are typically longer and don't follow the sk-ant- pattern
  if (credential.length > 100) {
    return "oauth_token";
  }
  
  // Default to API key for backward compatibility
  return "api_key";
}

/**
 * Get Anthropic authentication configuration
 * 
 * Priority:
 * 1. ANTHROPIC_OAUTH_TOKEN (if present, use OAuth)
 * 2. ANTHROPIC_API_KEY (traditional API key)
 * 3. Environment variables
 * 
 * @returns Authentication configuration or null if not configured
 */
export function getAnthropicAuth(): AnthropicConfig | null {
  // Try OAuth token first (explicit preference)
  const oauthToken = getConfigValue("ANTHROPIC_OAUTH_TOKEN") || process.env.ANTHROPIC_OAUTH_TOKEN;
  if (oauthToken) {
    logger.debug("Using Anthropic OAuth token authentication");
    return {
      authType: "oauth_token",
      credential: oauthToken,
    };
  }

  // Fallback to API key
  const apiKey = getConfigValue("ANTHROPIC_API_KEY") || process.env.ANTHROPIC_API_KEY;
  if (apiKey) {
    const authType = detectAuthType(apiKey);
    
    if (authType === "oauth_token") {
      logger.debug("Detected OAuth token format in ANTHROPIC_API_KEY");
    } else {
      logger.debug("Using Anthropic API key authentication");
    }
    
    return {
      authType,
      credential: apiKey,
    };
  }

  return null;
}

/**
 * Create Anthropic client with appropriate authentication
 * 
 * Handles both API key and OAuth token authentication.
 * OAuth tokens require different header configuration.
 * 
 * @param config Optional explicit configuration
 * @returns Configured Anthropic client
 * @throws Error if no authentication configured
 */
export function createAnthropicClient(config?: AnthropicConfig): Anthropic {
  const auth = config || getAnthropicAuth();

  if (!auth) {
    throw new Error(
      "Anthropic authentication not configured.\n" +
      "Please set either ANTHROPIC_API_KEY or ANTHROPIC_OAUTH_TOKEN in /etc/fazai/fazai.conf\n\n" +
      "API Key: Get from https://console.anthropic.com/\n" +
      "OAuth Token: Run `claude setup-token` (for Claude Code CLI users)"
    );
  }

  // For API keys, use standard SDK initialization
  if (auth.authType === "api_key") {
    return new Anthropic({
      apiKey: auth.credential,
    });
  }

  // For OAuth tokens, we need custom headers
  // Note: As of @anthropic-ai/sdk v0.24.3, OAuth support may require
  // custom fetch implementation or headers
  try {
    return new Anthropic({
      apiKey: auth.credential,
      // OAuth tokens may work with default apiKey field
      // If not, we might need to override fetch or headers
      // This would require testing with actual OAuth token
    });
  } catch (error) {
    logger.warn("OAuth token initialization failed, trying as API key:", error);
    
    // Fallback: try as regular API key
    return new Anthropic({
      apiKey: auth.credential,
    });
  }
}

/**
 * Check if Anthropic is configured (either API key or OAuth)
 * 
 * @returns True if any Anthropic authentication is available
 */
export function isAnthropicConfigured(): boolean {
  return getAnthropicAuth() !== null;
}

/**
 * Get authentication type currently configured
 * 
 * @returns Authentication type or null if not configured
 */
export function getConfiguredAuthType(): "api_key" | "oauth_token" | null {
  const auth = getAnthropicAuth();
  return auth ? auth.authType : null;
}
