#!/bin/bash
# =============================================================================
# Qdrant HA Cluster Setup Script
# =============================================================================
# Configura cluster HA entre walker (master) e papaimach (replica)
#
# Uso:
#   ./setup-cluster.sh [check|setup|replicate|status]
#
# Comandos:
#   check     - Verifica conectividade e estado atual
#   setup     - Exibe comandos para configurar o cluster (nao aplica)
#   replicate - Exibe comandos para replicar collections (nao aplica)
#   status    - Mostra status detalhado do cluster
#
# Variaveis de ambiente:
#   WALKER_HOST     - Host do master (default: walker)
#   PAPAIMACH_HOST  - Host da replica (default: papaimach)
#   QDRANT_API_KEY  - API key para autenticacao
#
# ATENCAO: Este script NAO aplica alteracoes automaticamente
#          Revise os comandos gerados antes de executar
# =============================================================================

set -euo pipefail

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuracao (pode ser sobrescrita por variaveis de ambiente)
WALKER_HOST="${WALKER_HOST:-walker}"
WALKER_PORT="${WALKER_PORT:-6333}"
WALKER_P2P="${WALKER_P2P:-6335}"

PAPAIMACH_HOST="${PAPAIMACH_HOST:-papaimach}"
PAPAIMACH_PORT="${PAPAIMACH_PORT:-6363}"
PAPAIMACH_P2P="${PAPAIMACH_P2P:-6335}"

API_KEY="${QDRANT_API_KEY:-}"

# Collections a replicar do walker para papaimach
REPLICATE_COLLECTIONS=(
    "fazai_learning"
        "fazai_memory"
            "fazai_inference"
                "fazai_kb"
                    "fazai_semantic_cache"
                        "fazai_source"
                            "fazai_personality"
                                "source"
                                    "terraforming"
                                    )

                                    log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
                                    log_ok() { echo -e "${GREEN}[OK]${NC} $*"; }
                                    log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
                                    log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

                                    check_health() {
                                        local host=$1
                                            local port=$2
                                                curl -sf "http://${host}:${port}/health" > /dev/null 2>&1
                                                }

                                                get_cluster_info() {
                                                    local host=$1
                                                        local port=$2
                                                            local headers=""
                                                                [[ -n "$API_KEY" ]] && headers="-H 'api-key: ${API_KEY}'"
                                                                    eval curl -sf $headers "http://${host}:${port}/cluster" 2>/dev/null || echo "{}"
                                                                    }

                                                                    get_peer_id() {
                                                                        local host=$1
                                                                            local port=$2
                                                                                get_cluster_info "$host" "$port" | jq -r '.result.peer_id // empty'
                                                                                }

                                                                                list_collections() {
                                                                                    local host=$1
                                                                                        local port=$2
                                                                                            local headers=""
                                                                                                [[ -n "$API_KEY" ]] && headers="-H 'api-key: ${API_KEY}'"
                                                                                                    eval curl -sf $headers "http://${host}:${port}/collections" 2>/dev/null | \
                                                                                                            jq -r '.result.collections[].name' 2>/dev/null || echo ""
                                                                                                            }
                                                                                                            
                                                                                                            cmd_check() {
                                                                                                                echo "============================================="
                                                                                                                    echo "QDRANT CLUSTER - VERIFICACAO"
                                                                                                                        echo "============================================="
                                                                                                                            echo ""
                                                                                                                                
                                                                                                                                    log_info "Verificando conectividade..."
                                                                                                                                        
                                                                                                                                            if check_health "$WALKER_HOST" "$WALKER_PORT"; then
                                                                                                                                                    log_ok "Walker (${WALKER_HOST}:${WALKER_PORT}): Acessivel"
                                                                                                                                                        else
                                                                                                                                                                log_error "Walker (${WALKER_HOST}:${WALKER_PORT}): Inacessivel"
                                                                                                                                                                    fi
                                                                                                                                                                        
                                                                                                                                                                            if check_health "$PAPAIMACH_HOST" "$PAPAIMACH_PORT"; then
                                                                                                                                                                                    log_ok "Papaimach (${PAPAIMACH_HOST}:${PAPAIMACH_PORT}): Acessivel"
                                                                                                                                                                                        else
                                                                                                                                                                                                log_error "Papaimach (${PAPAIMACH_HOST}:${PAPAIMACH_PORT}): Inacessivel"
                                                                                                                                                                                                    fi
                                                                                                                                                                                                        
                                                                                                                                                                                                            echo ""
                                                                                                                                                                                                                log_info "Verificando cluster..."
                                                                                                                                                                                                                    
                                                                                                                                                                                                                        local walker_peer=$(get_peer_id "$WALKER_HOST" "$WALKER_PORT")
                                                                                                                                                                                                                            local papaimach_peer=$(get_peer_id "$PAPAIMACH_HOST" "$PAPAIMACH_PORT")
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                    if [[ -n "$walker_peer" ]]; then
                                                                                                                                                                                                                                            log_ok "Walker Peer ID: $walker_peer"
                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                        log_warn "Walker: Cluster DESABILITADO"
                                                                                                                                                                                                                                                            fi
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    if [[ -n "$papaimach_peer" ]]; then
                                                                                                                                                                                                                                                                            log_ok "Papaimach Peer ID: $papaimach_peer"
                                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                                        log_warn "Papaimach: Cluster DESABILITADO"
                                                                                                                                                                                                                                                                                            fi
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                        log_info "Collections no Walker:"
                                                                                                                                                                                                                                                                                                            list_collections "$WALKER_HOST" "$WALKER_PORT" | sed 's/^/  - /'
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                        log_info "Collections no Papaimach:"
                                                                                                                                                                                                                                                                                                                            list_collections "$PAPAIMACH_HOST" "$PAPAIMACH_PORT" | sed 's/^/  - /'
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                            cmd_setup() {
                                                                                                                                                                                                                                                                                                                                echo "============================================="
                                                                                                                                                                                                                                                                                                                                    echo "COMANDOS PARA SETUP DO CLUSTER"
                                                                                                                                                                                                                                                                                                                                        echo "============================================="
                                                                                                                                                                                                                                                                                                                                            echo ""
                                                                                                                                                                                                                                                                                                                                                echo "# PASSO 1: Iniciar Walker como primeiro no do cluster"
                                                                                                                                                                                                                                                                                                                                                    echo "# Adicionar ao docker-compose ou comando de inicializacao:"
                                                                                                                                                                                                                                                                                                                                                        echo ""
                                                                                                                                                                                                                                                                                                                                                            echo "docker run -d \\"
                                                                                                                                                                                                                                                                                                                                                                echo "  --name qdrant-walker \\"
                                                                                                                                                                                                                                                                                                                                                                    echo "  -p ${WALKER_PORT}:6333 \\"
                                                                                                                                                                                                                                                                                                                                                                        echo "  -p 6334:6334 \\"
                                                                                                                                                                                                                                                                                                                                                                            echo "  -p ${WALKER_P2P}:6335 \\"
                                                                                                                                                                                                                                                                                                                                                                                echo "  -v qdrant-walker-data:/qdrant/storage \\"
                                                                                                                                                                                                                                                                                                                                                                                    echo "  -v ./docker/qdrant/config-walker.yaml:/qdrant/config/production.yaml \\"
                                                                                                                                                                                                                                                                                                                                                                                        echo "  -e QDRANT_API_KEY=\${QDRANT_API_KEY} \\"
                                                                                                                                                                                                                                                                                                                                                                                            echo "  qdrant/qdrant \\"
                                                                                                                                                                                                                                                                                                                                                                                                echo "  --uri 'http://${WALKER_HOST}:${WALKER_P2P}'"
                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                        echo "# PASSO 2: Iniciar Papaimach conectando ao cluster"
                                                                                                                                                                                                                                                                                                                                                                                                            echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                echo "docker run -d \\"
                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  --name qdrant-papaimach \\"
                                                                                                                                                                                                                                                                                                                                                                                                                        echo "  -p ${PAPAIMACH_PORT}:6333 \\"
                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  -p 6364:6334 \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                echo "  -p ${PAPAIMACH_P2P}:6335 \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  -v qdrant-papaimach-data:/qdrant/storage \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "  -v ./docker/qdrant/config-papaimach.yaml:/qdrant/config/production.yaml \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  -e QDRANT_API_KEY=\${QDRANT_API_KEY} \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "  qdrant/qdrant \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  --bootstrap 'http://${WALKER_HOST}:${WALKER_P2P}' \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "  --uri 'http://${PAPAIMACH_HOST}:${PAPAIMACH_P2P}'"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                        cmd_replicate() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "============================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "COMANDOS PARA REPLICACAO DE COLLECTIONS"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "============================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                local walker_peer=$(get_peer_id "$WALKER_HOST" "$WALKER_PORT")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    local papaimach_peer=$(get_peer_id "$PAPAIMACH_HOST" "$PAPAIMACH_PORT")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if [[ -z "$walker_peer" ]] || [[ -z "$papaimach_peer" ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    log_error "Cluster nao configurado. Execute 'setup' primeiro."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "# Walker Peer ID: $walker_peer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "# Papaimach Peer ID: $papaimach_peer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local auth_header=""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [[ -n "$API_KEY" ]] && auth_header="-H 'api-key: \${QDRANT_API_KEY}'"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for collection in "${REPLICATE_COLLECTIONS[@]}"; do
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "# Replicar: $collection"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "curl -X POST 'http://${WALKER_HOST}:${WALKER_PORT}/collections/${collection}/cluster' \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  -H 'Content-Type: application/json' \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [[ -n "$API_KEY" ]] && echo "  -H 'api-key: \${QDRANT_API_KEY}' \\"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  -d '{"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "    \"replicate_shard\": {"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "      \"shard_id\": 0,"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "      \"from_peer_id\": ${walker_peer},"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "      \"to_peer_id\": ${papaimach_peer},"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "      \"method\": \"snapshot\""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "    }"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  }'"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                done
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cmd_status() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "============================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "QDRANT CLUSTER - STATUS DETALHADO"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "============================================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        log_info "Walker Cluster Info:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            get_cluster_info "$WALKER_HOST" "$WALKER_PORT" | jq '.' 2>/dev/null || echo "N/A"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        log_info "Papaimach Cluster Info:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            get_cluster_info "$PAPAIMACH_HOST" "$PAPAIMACH_PORT" | jq '.' 2>/dev/null || echo "N/A"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            show_help() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "Uso: $0 [comando]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "Comandos:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  check     - Verifica conectividade e estado atual"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "  setup     - Exibe comandos para configurar o cluster"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  replicate - Exibe comandos para replicar collections"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "  status    - Mostra status detalhado do cluster"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "Variaveis de ambiente:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  WALKER_HOST     - Host do master (default: walker)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "  PAPAIMACH_HOST  - Host da replica (default: papaimach)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  QDRANT_API_KEY  - API key para autenticacao"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case "${1:-check}" in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                check)     cmd_check ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setup)     cmd_setup ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        replicate) cmd_replicate ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status)    cmd_status ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                help|-h|--help) show_help ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    *) log_error "Comando desconhecido: $1"; show_help; exit 1 ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    esac
