/**
 * FazAI Completion Command
 *
 * Generates and manages bash/zsh completion scripts with auto-discovery.
 * Uses the same source of truth as scripts/generate-completions.js
 *
 * Usage:
 *   fazai completion              # Show help
 *   fazai completion bash         # Output bash completion script
 *   fazai completion zsh          # Output zsh completion script
 *   fazai completion install      # Install to system
 *   fazai completion list         # List available commands (legacy)
 */

import chalk from "chalk";
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { models } from "../models";
import { logger } from "../logger";
import { getConfigValue } from "../config";

// Source of truth: same as SUBCOMMANDS_WITH_HELP in app.ts
const COMMANDS = [
  "qdrant",
  "vector",
  "ask",
  "import",
  "alias",
  "cloudflare",
  "cf",
  "github",
  "index",
  "sync",
  "config",
  "search",
  "inference",
  "agent",
  "ingest",
  "dashboard",
  "samba",
  "completion",
];

const SUBCOMMANDS: Record<string, string[]> = {
  qdrant: ["status", "metrics", "backup", "restore", "import", "export", "container", "collections", "help"],
  vector: ["validate", "recreate", "reset"],
  alias: ["list", "ls", "show", "remove", "rm", "delete"],
  github: ["auth", "user", "repos", "issues", "fork", "star", "pr", "help"],
  cloudflare: ["zones", "dns", "workers", "purge", "analytics"],
  cf: ["zones", "dns", "workers", "purge", "analytics"],
  inference: ["add", "import", "list", "search", "remove", "clear", "help"],
  agent: ["loop", "run", "reflect", "status", "scripts", "help"],
  dashboard: ["start", "stop", "status", "help"],
  samba: ["list", "add", "del", "criauser", "criadir", "criagroup", "completion", "help"],
  completion: ["bash", "zsh", "install", "list", "help"],
};

const OPTIONS = [
  "--dry-run",
  "--cli",
  "--debug",
  "--verbose",
  "--log-file",
  "--auto-research",
  "--yolo",
  "-y",
  "--semantic",
  "--help",
  "-h",
];

function showCompletionHelp(): void {
  console.log(chalk.bold.cyan("\n🔧 FazAI Completion Command\n"));
  console.log("Generate and manage shell completion scripts.\n");

  console.log(chalk.bold("USAGE:"));
  console.log("  fazai completion <subcommand>\n");

  console.log(chalk.bold("SUBCOMMANDS:"));
  console.log("  bash       Output bash completion script to stdout");
  console.log("  zsh        Output zsh completion script to stdout");
  console.log("  install    Install completion to system (/etc/bash_completion.d/)");
  console.log("  list       List available commands and models (legacy)");
  console.log("  help       Show this help message\n");

  console.log(chalk.bold("EXAMPLES:"));
  console.log("  fazai completion bash > /tmp/fazai.bash");
  console.log("  fazai completion zsh > ~/.zsh/completion/_fazai");
  console.log("  sudo fazai completion install");
  console.log("  fazai completion list\n");

  console.log(chalk.bold("INSTALLATION:"));
  console.log(chalk.dim("  # Bash (system-wide)"));
  console.log("  sudo fazai completion install\n");
  console.log(chalk.dim("  # Bash (user)"));
  console.log("  fazai completion bash >> ~/.bashrc\n");
  console.log(chalk.dim("  # Zsh"));
  console.log("  mkdir -p ~/.zsh/completion");
  console.log("  fazai completion zsh > ~/.zsh/completion/_fazai");
  console.log("  echo 'fpath=(~/.zsh/completion $fpath)' >> ~/.zshrc");
  console.log("  echo 'autoload -Uz compinit && compinit' >> ~/.zshrc\n");
}

function generateBashCompletion(): string {
  const commandsList = COMMANDS.join(" ");
  const optionsList = OPTIONS.join(" ");
  const modelsList = models.map((m) => m.name).join(" ");

  // Generate case statements for commands with subcommands
  const subcommandCases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => {
      const subcmds = subs.join(" ");
      return `        ${cmd})
            local subcmds="${subcmds}"
            COMPREPLY=( $(compgen -W "\${subcmds}" -- \${cur}) )
            return 0
            ;;`;
    })
    .join("\n");

  return `#!/usr/bin/env bash
# Bash completion for FazAI - Generated by 'fazai completion bash'
# Source of truth: COMMANDS array in src/commands/completion.ts
#
# Installation:
#   sudo fazai completion install
# Or:
#   fazai completion bash > /etc/bash_completion.d/fazai
# Or:
#   fazai completion bash >> ~/.bashrc

# Load models dynamically from fazai.conf at runtime
_fazai_load_models() {
    local config_file="\${FAZAI_CONFIG_PATH:-/etc/fazai/fazai.conf}"

    if [[ -r "\$config_file" ]]; then
        grep '^MODELS_' "\$config_file" 2>/dev/null | awk -F'=' '{print \$2}' | tr ',' ' ' | tr -s ' '
    fi
}

_fazai_completion() {
    local cur prev opts commands models subcmds
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    # Main commands
    commands="${commandsList}"

    # Options/flags
    opts="${optionsList}"

    # AI models (loaded dynamically from /etc/fazai/fazai.conf)
    if [[ -z "\$FAZAI_MODELS_CACHE" ]]; then
        FAZAI_MODELS_CACHE=\$(_fazai_load_models)
    fi
    models="\$FAZAI_MODELS_CACHE"

    # Fallback models if config not available
    if [[ -z "\$models" ]]; then
        models="${modelsList}"
    fi

    # First argument (command or model)
    if [[ \$COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( \$(compgen -W "\$commands \$models \$opts" -- \${cur}) )
        return 0
    fi

    # Handle specific commands with subcommands
    case "\${COMP_WORDS[1]}" in
${subcommandCases}

        ask)
            COMPREPLY=( \$(compgen -W "\$models" -- \${cur}) )
            return 0
            ;;

        import)
            case "\${prev}" in
                import)
                    COMPREPLY=( \$(compgen -f -- \${cur}) )
                    return 0
                    ;;
                --source)
                    COMPREPLY=( \$(compgen -W "claude chatgpt" -- \${cur}) )
                    return 0
                    ;;
                *)
                    if [[ \${cur} == -* ]]; then
                        COMPREPLY=( \$(compgen -W "--source --recursive -r --no-knowledge --no-learning" -- \${cur}) )
                    else
                        COMPREPLY=( \$(compgen -f -- \${cur}) )
                    fi
                    return 0
                    ;;
            esac
            ;;

        *)
            COMPREPLY=( \$(compgen -W "\${opts}" -- \${cur}) )
            return 0
            ;;
    esac
}

complete -F _fazai_completion fazai
`;
}

function generateZshCompletion(): string {
  const commandsZsh = COMMANDS.map((c) => `'${c}:${c} command'`).join("\n        ");
  const modelsZsh = models.map((m) => `'${m.name}:${m.provider} model'`).join("\n        ");
  const optsZsh = OPTIONS.map((o) => `'${o}:option'`).join("\n        ");

  // Generate subcommand cases
  const subcommandCases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => {
      const subcmdsZsh = subs.map((s) => `'${s}:${s} subcommand'`).join("\n                ");
      return `        ${cmd})
            local -a ${cmd}_cmds
            ${cmd}_cmds=(
                ${subcmdsZsh}
            )
            _describe '${cmd} subcommands' ${cmd}_cmds
            ;;`;
    })
    .join("\n");

  return `#compdef fazai
# Zsh completion for FazAI - Generated by 'fazai completion zsh'
# Source of truth: COMMANDS array in src/commands/completion.ts
#
# Installation:
#   mkdir -p ~/.zsh/completion
#   fazai completion zsh > ~/.zsh/completion/_fazai
#   Add to ~/.zshrc: fpath=(~/.zsh/completion $fpath)
#   Run: autoload -Uz compinit && compinit

_fazai_load_models() {
    local config_file="\${FAZAI_CONFIG_PATH:-/etc/fazai/fazai.conf}"

    if [[ -r "\$config_file" ]]; then
        grep '^MODELS_' "\$config_file" 2>/dev/null | cut -d'=' -f2 | tr ',' '\\n'
    fi
}

_fazai() {
    local -a commands models opts

    commands=(
        ${commandsZsh}
    )

    if [[ -z "\$FAZAI_MODELS_CACHE_ZSH" ]]; then
        FAZAI_MODELS_CACHE_ZSH=(\${(f)"\$(_fazai_load_models)"})
    fi
    models=("\$FAZAI_MODELS_CACHE_ZSH[@]")

    # Fallback models
    if [[ \${#models[@]} -eq 0 ]]; then
        models=(
            ${modelsZsh}
        )
    fi

    opts=(
        ${optsZsh}
    )

    _arguments \\
        '1:command:->command' \\
        '*::arg:->args'

    case "\$state" in
        command)
            _describe 'fazai commands' commands
            _describe 'fazai models' models
            _describe 'fazai options' opts
            ;;

        args)
            case "\$words[1]" in
${subcommandCases}

                ask)
                    _describe 'fazai models' models
                    ;;

                import)
                    _arguments \\
                        '1:file:_files' \\
                        '--source[Source platform]:source:(claude chatgpt)' \\
                        '--recursive[Process directory recursively]' \\
                        '-r[Process directory recursively]'
                    ;;
            esac
            ;;
    esac
}

_fazai "\$@"
`;
}

function installCompletion(): void {
  const bashScript = generateBashCompletion();
  const targetPath = "/etc/bash_completion.d/fazai";

  try {
    // Check if we have write permission
    fs.accessSync("/etc/bash_completion.d", fs.constants.W_OK);

    fs.writeFileSync(targetPath, bashScript, { mode: 0o644 });
    console.log(chalk.green(`✅ Completion installed to ${targetPath}`));
    console.log(chalk.dim("   Run 'exec bash' or open a new terminal to activate"));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "EACCES") {
      console.log(chalk.red("❌ Permission denied. Run with sudo:"));
      console.log(chalk.yellow("   sudo fazai completion install"));
    } else {
      console.log(chalk.red(`❌ Error: ${(error as Error).message}`));
    }
    process.exit(1);
  }
}

function listCompletions(): void {
  // Legacy behavior: list commands, options, and models
  const suggestions = [
    ...COMMANDS,
    ...OPTIONS,
    ...models.map((m) => m.name),
  ];
  console.log(suggestions.join("\n"));
}

export async function handleCompletionCommand(args: string[]): Promise<void> {
  const subcommand = args[0]?.toLowerCase();

  if (!subcommand || subcommand === "help" || subcommand === "--help" || subcommand === "-h") {
    showCompletionHelp();
    return;
  }

  switch (subcommand) {
    case "bash":
      console.log(generateBashCompletion());
      break;

    case "zsh":
      console.log(generateZshCompletion());
      break;

    case "install":
      installCompletion();
      break;

    case "list":
      listCompletions();
      break;

    default:
      console.log(chalk.yellow(`Unknown subcommand: ${subcommand}`));
      showCompletionHelp();
      process.exit(1);
  }
}

export { COMMANDS, SUBCOMMANDS, OPTIONS };
