#!/usr/bin/env bash
# Bash completion for FazAI - AUTO-GENERATED (DO NOT EDIT MANUALLY)
# Generated by: scripts/generate-completions.js
# Source of truth: src/app.ts (SUBCOMMANDS_WITH_HELP) + src/models.ts
#
# Installation:
#   sudo cp completion/fazai-completion.bash /etc/bash_completion.d/fazai
# Or:
#   source completion/fazai-completion.bash

# Load models dynamically from fazai.conf at runtime
_fazai_load_models() {
    local config_file="${FAZAI_CONFIG_PATH:-/etc/fazai/fazai.conf}"

    if [[ -r "$config_file" ]]; then
        grep '^MODELS_' "$config_file" 2>/dev/null | awk -F'=' '{print $2}' | tr ',' ' ' | tr -s ' '
    fi
}

_fazai_completion() {
    local cur prev opts commands models subcmds
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Main commands (auto-discovered from SUBCOMMANDS_WITH_HELP)
    commands="qdrant vector ask import alias cloudflare cf github index sync config search inference agent ingest dashboard samba completion"

    # Options/flags (auto-discovered from app.ts)
    opts="--dry-run --cli --debug --verbose --log-file --auto-research --yolo --semantic --help -y -h"

    # AI models (loaded dynamically from /etc/fazai/fazai.conf)
    if [[ -z "$FAZAI_MODELS_CACHE" ]]; then
        FAZAI_MODELS_CACHE=$(_fazai_load_models)
    fi
    models="$FAZAI_MODELS_CACHE"

    # First argument (command or model)
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$commands $models $opts" -- ${cur}) )
        return 0
    fi

    # Handle specific commands with subcommands
    case "${COMP_WORDS[1]}" in
        qdrant)
            local subcmds="backup container export import logs metrics recommend recommendations restart restore start status stop"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        alias)
            local subcmds="delete list ls remove rm show"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        cloudflare)
            local subcmds="cache dns ssl worker workers zone zones"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        cf)
            local subcmds="cache dns ssl worker workers zone zones"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        github)
            local subcmds="auth fork help issue issues pr repo repos star starred user"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        inference)
            local subcmds="add clear import list remove search"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        agent)
            local subcmds="help loop native reflect run scripts status --help -h"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        ingest)
            local subcmds="--batch --preview --help"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        dashboard)
            local subcmds="start status stop --host --no-cors --no-logs --no-rate-limit --port"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        samba)
            local subcmds="add completion criadir criagroup criauser del list"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;
        completion)
            local subcmds="bash zsh install list help"
            COMPREPLY=( $(compgen -W "${subcmds}" -- ${cur}) )
            return 0
            ;;

        ask)
            # Model names for ask command
            COMPREPLY=( $(compgen -W "$models" -- ${cur}) )
            return 0
            ;;

        import)
            case "${prev}" in
                import)
                    COMPREPLY=( $(compgen -f -- ${cur}) )
                    return 0
                    ;;
                --source)
                    COMPREPLY=( $(compgen -W "claude chatgpt" -- ${cur}) )
                    return 0
                    ;;
                *)
                    if [[ ${cur} == -* ]]; then
                        COMPREPLY=( $(compgen -W "--source --recursive -r --no-knowledge --no-learning" -- ${cur}) )
                    else
                        COMPREPLY=( $(compgen -f -- ${cur}) )
                    fi
                    return 0
                    ;;
            esac
            ;;

        alias)
            case "${prev}" in
                alias)
                    local alias_cmds="list ls show remove rm delete"
                    if [[ -f /etc/fazai/fzalias ]]; then
                        local aliases=$(grep "^alias " /etc/fazai/fzalias 2>/dev/null | sed "s/^alias \([^=]*\)=.*/\1/")
                        COMPREPLY=( $(compgen -W "${alias_cmds} ${aliases}" -- ${cur}) )
                    else
                        COMPREPLY=( $(compgen -W "${alias_cmds}" -- ${cur}) )
                    fi
                    return 0
                    ;;
                *)
                    COMPREPLY=( $(compgen -W "list ls show remove rm delete" -- ${cur}) )
                    return 0
                    ;;
            esac
            ;;

        samba)
            case "${prev}" in
                add|criadir)
                    COMPREPLY=( $(compgen -d -- ${cur}) )
                    return 0
                    ;;
                del)
                    if [[ -r /etc/samba/smb.conf ]]; then
                        local shares=$(awk -F'[][]' '/^\[.*\]$/{print $2}' /etc/samba/smb.conf 2>/dev/null | grep -v '^global$')
                        COMPREPLY=( $(compgen -W "${shares}" -- ${cur}) )
                    fi
                    return 0
                    ;;
                criauser)
                    COMPREPLY=( $(compgen -u -- ${cur}) )
                    return 0
                    ;;
                criagroup)
                    COMPREPLY=( $(compgen -g -- ${cur}) )
                    return 0
                    ;;
            esac
            ;;

        github)
            case "${prev}" in
                auth)
                    COMPREPLY=( $(compgen -W "login logout status" -- ${cur}) )
                    return 0
                    ;;
            esac
            ;;

        inference)
            case "${prev}" in
                add|import)
                    if [[ ${cur} == -* ]]; then
                        COMPREPLY=( $(compgen -W "--category=doc --category=rule --category=example --category=fact" -- ${cur}) )
                    fi
                    return 0
                    ;;
            esac
            ;;

        *)
            # Default: options
            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
            return 0
            ;;
    esac
}

# Register completion
complete -F _fazai_completion fazai
