#compdef fazai
# Zsh completion for FazAI - AUTO-GENERATED (DO NOT EDIT MANUALLY)
# Generated by: scripts/generate-completions.js
# Source of truth: src/app.ts (SUBCOMMANDS_WITH_HELP) + src/models.ts
#
# Installation:
#   mkdir -p ~/.zsh/completion
#   cp completion/fazai-completion.zsh ~/.zsh/completion/_fazai
#   Add to ~/.zshrc: fpath=(~/.zsh/completion $fpath)
#   Run: autoload -Uz compinit && compinit

# Load models dynamically from fazai.conf
_fazai_load_models() {
    local config_file="${FAZAI_CONFIG_PATH:-/etc/fazai/fazai.conf}"

    if [[ -r "$config_file" ]]; then
        grep '^MODELS_' "$config_file" 2>/dev/null | cut -d'=' -f2 | tr ',' '\n'
    fi
}

_fazai() {
    local -a commands models opts

    commands=(
        'qdrant:Qdrant management (status, metrics, backup, etc)'
        'vector:Valida collections vetoriais (Qdrant)'
        'ask:General AI questions'
        'import:Importa conversas para Qdrant'
        'alias:Create/manage global bash aliases'
        'cloudflare:Manage Cloudflare (zones, dns, workers)'
        'cf:Cloudflare: list zones'
        'github:GitHub integration (auth, repos, issues, etc)'
        'index:Gerencia o índice de metacognição (código fonte)'
        'sync:Sincroniza configurações e scripts (dotfiles)'
        'config:List configured API keys'
        'search:Manual research via Context7/Web (supports SPAs)'
        'inference:Gerencia conhecimento injetado pelo usuário'
        'agent:Executa agentes GenAIScript (loop, reflect, etc)'
        'ingest:Personality data ingestion'
        'dashboard:Gerencia REST API Dashboard (start, stop, status)'
        'samba:Gerencia compartilhamentos Samba (list, add, del, etc)'
        'completion:Print available CLI completions'
        'cleaner:Semantic file cleaner (archive orphan/deprecated files)'
        'skill-seeker:skill-seeker command'
    )

    # Load models dynamically (cached)
    if [[ -z "$FAZAI_MODELS_CACHE_ZSH" ]]; then
        FAZAI_MODELS_CACHE_ZSH=(${(f)"$(_fazai_load_models)"})
    fi
    models=("$FAZAI_MODELS_CACHE_ZSH[@]")

    opts=(
        '--dry-run:Simulate commands without executing'
        '--cli:Open interactive CLI mode'
        '--debug:Enable debug logging'
        '--verbose:Enable verbose logging'
        '--log-file:Specify log file path'
        '--auto-research:Re-enable automatic research on failures'
        '--yolo:Skip confirmations (dangerous!)'
        '--semantic:Enable semantic search'
        '--help:Show help message'
        '-y:Skip confirmations (dangerous!)'
        '-h:Show help message'
    )

    _arguments \
        '1:command:->command' \
        '*::arg:->args'

    case "$state" in
        command)
            _describe 'fazai commands' commands
            _describe 'fazai models' models
            _describe 'fazai options' opts
            ;;

        args)
            case "$words[1]" in
        qdrant)
            local -a qdrant_cmds
            qdrant_cmds=(
                'backup:backup subcommand'
                'container:container subcommand'
                'export:export subcommand'
                'import:import subcommand'
                'logs:logs subcommand'
                'metrics:metrics subcommand'
                'recommend:recommend subcommand'
                'recommendations:recommendations subcommand'
                'restart:restart subcommand'
                'restore:restore subcommand'
                'start:start subcommand'
                'status:status subcommand'
                'stop:stop subcommand'
            )
            _describe 'qdrant subcommands' qdrant_cmds
            ;;
        alias)
            local -a alias_cmds
            alias_cmds=(
                'delete:delete subcommand'
                'list:list subcommand'
                'ls:ls subcommand'
                'remove:remove subcommand'
                'rm:rm subcommand'
                'show:show subcommand'
            )
            _describe 'alias subcommands' alias_cmds
            ;;
        cloudflare)
            local -a cloudflare_cmds
            cloudflare_cmds=(
                'cache:cache subcommand'
                'dns:dns subcommand'
                'ssl:ssl subcommand'
                'worker:worker subcommand'
                'workers:workers subcommand'
                'zone:zone subcommand'
                'zones:zones subcommand'
            )
            _describe 'cloudflare subcommands' cloudflare_cmds
            ;;
        cf)
            local -a cf_cmds
            cf_cmds=(
                'cache:cache subcommand'
                'dns:dns subcommand'
                'ssl:ssl subcommand'
                'worker:worker subcommand'
                'workers:workers subcommand'
                'zone:zone subcommand'
                'zones:zones subcommand'
            )
            _describe 'cf subcommands' cf_cmds
            ;;
        github)
            local -a github_cmds
            github_cmds=(
                'auth:auth subcommand'
                'fork:fork subcommand'
                'help:help subcommand'
                'issue:issue subcommand'
                'issues:issues subcommand'
                'pr:pr subcommand'
                'repo:repo subcommand'
                'repos:repos subcommand'
                'star:star subcommand'
                'starred:starred subcommand'
                'user:user subcommand'
            )
            _describe 'github subcommands' github_cmds
            ;;
        inference)
            local -a inference_cmds
            inference_cmds=(
                'add:add subcommand'
                'clear:clear subcommand'
                'import:import subcommand'
                'list:list subcommand'
                'remove:remove subcommand'
                'search:search subcommand'
            )
            _describe 'inference subcommands' inference_cmds
            ;;
        agent)
            local -a agent_cmds
            agent_cmds=(
                'help:help subcommand'
                'loop:loop subcommand'
                'native:native subcommand'
                'reflect:reflect subcommand'
                'run:run subcommand'
                'scripts:scripts subcommand'
                'status:status subcommand'
                '--help:--help subcommand'
                '-h:-h subcommand'
            )
            _describe 'agent subcommands' agent_cmds
            ;;
        ingest)
            local -a ingest_cmds
            ingest_cmds=(
                '--batch:--batch subcommand'
                '--preview:--preview subcommand'
                '--help:--help subcommand'
            )
            _describe 'ingest subcommands' ingest_cmds
            ;;
        dashboard)
            local -a dashboard_cmds
            dashboard_cmds=(
                'start:start subcommand'
                'status:status subcommand'
                'stop:stop subcommand'
                '--host:--host subcommand'
                '--no-cors:--no-cors subcommand'
                '--no-logs:--no-logs subcommand'
                '--no-rate-limit:--no-rate-limit subcommand'
                '--port:--port subcommand'
            )
            _describe 'dashboard subcommands' dashboard_cmds
            ;;
        samba)
            local -a samba_cmds
            samba_cmds=(
                'add:add subcommand'
                'completion:completion subcommand'
                'criadir:criadir subcommand'
                'criagroup:criagroup subcommand'
                'criauser:criauser subcommand'
                'del:del subcommand'
                'list:list subcommand'
            )
            _describe 'samba subcommands' samba_cmds
            ;;
        completion)
            local -a completion_cmds
            completion_cmds=(
                'bash:bash subcommand'
                'zsh:zsh subcommand'
                'install:install subcommand'
                'list:list subcommand'
                'help:help subcommand'
            )
            _describe 'completion subcommands' completion_cmds
            ;;
        cleaner)
            local -a cleaner_cmds
            cleaner_cmds=(
                '--exec:--exec subcommand'
                '--dry-run:--dry-run subcommand'
                '--help:--help subcommand'
            )
            _describe 'cleaner subcommands' cleaner_cmds
            ;;

                ask)
                    _describe 'fazai models' models
                    ;;

                import)
                    _arguments \
                        '1:file:_files' \
                        '--source[Source platform]:source:(claude chatgpt)' \
                        '--recursive[Process directory recursively]' \
                        '-r[Process directory recursively]' \
                        '--no-knowledge[Skip knowledge extraction]' \
                        '--no-learning[Skip learning extraction]'
                    ;;

                samba)
                    case "$words[2]" in
                        add|criadir)
                            _files -/
                            ;;
                        del)
                            local -a shares
                            shares=(${(f)"$(awk -F'[][]' '/^\[.*\]$/{print $2}' /etc/samba/smb.conf 2>/dev/null | grep -v '^global$')"})
                            _describe 'samba shares' shares
                            ;;
                        criauser)
                            _users
                            ;;
                        criagroup)
                            _groups
                            ;;
                    esac
                    ;;

                github)
                    case "$words[2]" in
                        auth)
                            _describe 'auth actions' '(login logout status)'
                            ;;
                    esac
                    ;;
            esac
            ;;
    esac
}

_fazai "$@"
