/**
 * Claude Skill Converter
 * 
 * Parses a target directory containing a Claude-style .claude/SKILL.md file
 * (with YAML frontmatter and markdown body) and converts it into a FazAI
 * native .genai.mjs script in the genaisrc/ directory.
 * 
 * @module skills/claude-converter
 */

import * as fs from "fs/promises";
import * as path from "path";
import { logger } from "../logger.js";
import { getConfigValue } from "../config.js";
import { getSkillRegistry, SkillDefinition } from "./registry.js";

interface ParsedClaudeSkill {
  name: string;
  description: string;
  instructions: string;
  model?: string;
}

/**
 * Claude Converter Skill Implementation
 */
export const claudeConverterSkill: SkillDefinition = {
  id: "claude-import",
  name: "Claude Skill Converter",
  description: "Imports a Claude-style skill (.claude/SKILL.md) and converts it to a FazAI GenAIScript",
  category: "custom",
  permissionLevel: "medium",
  source: "runtime",
  inputSchema: {
    type: "object",
    properties: {
      targetPath: {
        type: "string",
        description: "Path to the directory containing .claude/SKILL.md or the SKILL.md file itself",
      },
    },
    required: ["targetPath"],
  },
  handler: async (input: Record<string, unknown>) => {
    const targetPath = input.targetPath as string;
    if (!targetPath) {
      return { success: false, output: "", duration: 0, error: "targetPath is required" };
    }

    try {
      // 1. Resolve path to SKILL.md
      let skillFilePath = path.resolve(process.cwd(), targetPath);
      const stat = await fs.stat(skillFilePath).catch(() => null);
      
      if (!stat) {
        return { success: false, output: "", duration: 0, error: `Path not found: ${skillFilePath}` };
      }

      if (stat.isDirectory()) {
        skillFilePath = path.join(skillFilePath, ".claude", "SKILL.md");
        const skillStat = await fs.stat(skillFilePath).catch(() => null);
        if (!skillStat) {
          // Try root of directory just in case
          skillFilePath = path.join(targetPath, "SKILL.md");
          const fallbackStat = await fs.stat(skillFilePath).catch(() => null);
          if (!fallbackStat) {
            return { success: false, output: "", duration: 0, error: `SKILL.md not found in ${targetPath} or ${targetPath}/.claude/` };
          }
        }
      } else if (!skillFilePath.endsWith("SKILL.md")) {
        return { success: false, output: "", duration: 0, error: `Target file must be named SKILL.md` };
      }

      // 2. Parse YAML Frontmatter and Markdown Body
      const content = await fs.readFile(skillFilePath, "utf-8");
      const parsed = parseClaudeSkill(content);
      
      if (!parsed.name || !parsed.description) {
        return { success: false, output: "", duration: 0, error: "Invalid SKILL.md: Missing name or description in YAML frontmatter" };
      }

      // Normalize name for filename (e.g. "My Skill" -> "my-skill")
      const safeName = parsed.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
      const fileName = `${safeName}.genai.mjs`;
      
      const genaiSrcDir = path.resolve(process.cwd(), getConfigValue("GENAISRC_DIR") || "genaisrc");
      
      // Ensure directory exists
      await fs.mkdir(genaiSrcDir, { recursive: true }).catch(() => {});
      
      const outputPath = path.join(genaiSrcDir, fileName);

      // 3. Idempotency Check
      const outStat = await fs.stat(outputPath).catch(() => null);
      if (outStat) {
        return {
          success: true,
          output: `Skill '${parsed.name}' already exists at ${outputPath}. Run 'fazai agent use ${safeName}' to execute it.`,
          duration: 0,
        };
      }

      // 4. Generate .genai.mjs content
      const theModel = parsed.model || "ollama:phi3";
      
      // Escape backticks in markdown instructions
      const escapedInstructions = parsed.instructions.replace(/`/g, "\\`");

      const scriptContent = `/**
 * Auto-generated by FazAI Claude Converter
 * Imported from: ${skillFilePath}
 */

script({
  title: "${parsed.name}",
  description: "${parsed.description}",
  model: env.vars.model || "${theModel}",
  system: ["system", "files"],
  temperature: 0.1
});

// Import instructions as system prompt
$` + "`" + `
${escapedInstructions}
` + "`" + `;

// Process user input
const inputStr = env.vars.query || env.vars.input || "";
if (inputStr) {
  $` + "`" + `
User Request:
---
\${inputStr}
---
` + "`" + `;
} else {
  $` + "`" + `Execute your primary directive based on the instructions above.` + "`" + `;
}
`;

      // 5. Write file
      await fs.writeFile(outputPath, scriptContent, "utf-8");
      
      // 6. Register in running registry so we don't need a restart
      const registry = getSkillRegistry();
      // It will auto-discover next boot, but we can do a quick manual registration
      // by triggering a re-discovery (which is safe and deduplicates)
      await registry.discover();
      
      logger.info(`[ClaudeConverter] Successfully imported skill '${parsed.name}' to ${outputPath}`);
      
      return {
        success: true,
        output: `Successfully converted Claude skill!\nName: ${parsed.name}\nDescription: ${parsed.description}\nFile created: ${outputPath}\n\nTo use this skill, run:\n  fazai agent use ${safeName} --mode analyze`,
        duration: 0,
      };
      
    } catch (error: any) {
      logger.error(`[ClaudeConverter] Error: ${error.message}`);
      return { success: false, output: "", duration: 0, error: `Conversion failed: ${error.message}` };
    }
  }
};

/**
 * Super simple YAML frontmatter parser for our limited needs
 * Doesn't require a full yaml library dependency
 */
function parseClaudeSkill(content: string): ParsedClaudeSkill {
  const result: ParsedClaudeSkill = {
    name: "",
    description: "",
    instructions: "",
  };

  const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/;
  const match = content.match(frontmatterRegex);

  if (match) {
    const yaml = match[1];
    result.instructions = match[2].trim();

    // Parse primitive pairs
    const lines = yaml.split("\n");
    for (const line of lines) {
      const parts = line.split(":");
      if (parts.length >= 2) {
        const key = parts[0].trim().toLowerCase();
        // Join the rest in case there are multiple colons in the value
        const val = parts.slice(1).join(":").trim().replace(/^['"]|['"]$/g, "");
        
        if (key === "name") result.name = val;
        else if (key === "description") result.description = val;
        else if (key === "model") result.model = val;
      }
    }
  } else {
    // No frontmatter found, treat whole file as instructions
    result.instructions = content.trim();
  }

  return result;
}
