version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - fazai-monitor-net

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - fazai-monitor-net

networks:
  fazai-monitor-net:
    driver: bridge
